FROM openvino:latest

WORKDIR /opt/intel/openvino_2020.2.120/deployment_tools/open_model_zoo/demos/
RUN bash -C "./build_demos.sh"

WORKDIR /opt/intel/openvino_2020.2.120/deployment_tools/tools/model_downloader
RUN python3 downloader.py --name vehicle-license-plate-detection-barrier-0106
RUN python3 downloader.py --name vehicle-attributes-recognition-barrier-0039
RUN python3 downloader.py --name license-plate-recognition-barrier-0001

CMD bash -c "cd /opt/intel/openvino_2020.2.120/bin/ && \
             source setupvars.sh && \
             cd /root/omz_demos_build/intel64/Release/ && \
             ./security_barrier_camera_demo -i /dev/video0 -m /opt/intel/openvino_2020.2.120/deployment_tools/open_model_zoo/tools/downloader/intel/vehicle-license-plate-detection-barrier-0106/FP32/vehicle-license-plate-detection-barrier-0106.xml -m_va /opt/intel/openvino_2020.2.120/deployment_tools/open_model_zoo/tools/downloader/intel/vehicle-attributes-recognition-barrier-0039/FP32/vehicle-attributes-recognition-barrier-0039.xml -m_lpr /opt/intel/openvino_2020.2.120/deployment_tools/open_model_zoo/tools/downloader/intel/license-plate-recognition-barrier-0001/FP32/license-plate-recognition-barrier-0001.xml"

