FROM openvino:latest

WORKDIR /opt/intel/openvino_2020.2.120/deployment_tools/open_model_zoo/demos/
RUN bash -C "./build_demos.sh"

WORKDIR /opt/intel/openvino_2020.2.120/deployment_tools/tools/model_downloader
RUN python3 downloader.py --name face-detection-adas-0001
RUN python3 downloader.py --name age-gender-recognition-retail-0013
RUN python3 downloader.py --name head-pose-estimation-adas-0001
RUN python3 downloader.py --name emotions-recognition-retail-0003
RUN python3 downloader.py --name facial-landmarks-35-adas-0002

CMD bash -c "cd /opt/intel/openvino_2020.2.120/bin/ && \
             source setupvars.sh && \
             cd /root/omz_demos_build/intel64/Release/ && \
             ./interactive_face_detection_demo -i cam -m /opt/intel/openvino_2020.2.120/deployment_tools/open_model_zoo/tools/downloader/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml -m_ag /opt/intel/openvino_2020.2.120/deployment_tools/open_model_zoo/tools/downloader/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml -m_hp /opt/intel/openvino_2020.2.120/deployment_tools/open_model_zoo/tools/downloader/intel/head-pose-estimation-adas-0001/FP32/head-pose-estimation-adas-0001.xml"

